// make one target with all tests

#include "branched.hpp"
#include "continual.hpp"
#include "recurrent.hpp"
#include "recursive.hpp"

// main() will be generated by catch2 (linking with Catch2::Catch2WithMain)