// make one target with all tests

// clang-format off
#include "branched.hpp"
#include "continual.hpp"
#include "recurrent.hpp"
#include "recursive.hpp"
#include "error_cases.hpp"
#include "throw_lua_errors.hpp"
#include "regex.hpp"
// clang-format on

// main() will be generated by catch2 (linking with Catch2::Catch2WithMain)